apiVersion: v1
kind: Service
metadata:
  name: alert-manager-api
  namespace: alert-manager
  labels:
    app: alert-manager-api
    component: api
spec:
  type: LoadBalancer  # Exponer externamente
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: alert-manager-api
