apiVersion: v1
kind: ConfigMap
metadata:
  name: alert-manager-config
  namespace: alert-manager
data:
  # Base de datos principal
  POSTGRES_USER: "postgres"
  POSTGRES_DB: "alert_manager"
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"
  
  # Airflow
  AIRFLOW__CORE__EXECUTOR: "LocalExecutor"
  AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "false"
  AIRFLOW__CORE__LOAD_EXAMPLES: "false"
  AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "true"
  AIRFLOW__API__AUTH_BACKENDS: "airflow.api.auth.backend.basic_auth"
  AIRFLOW__WEBSERVER__SECRET_KEY: "airflow-secret-key"
  
  # Airflow DB
  AIRFLOW_DB_NAME: "airflow"
  AIRFLOW_DB_USER: "airflow"
  AIRFLOW_DB_HOST: "airflow-db"
  AIRFLOW_DB_PORT: "5432"
  
  # Logging
  LOG_LEVEL: "INFO"
  SEQ_URL: "http://seq:5341"
  
  # API
  PYTHONPATH: "/app/src"
  ENVIRONMENT: "production"
