apiVersion: v1
kind: Service
metadata:
  name: airflow-webserver
  namespace: alert-manager
  labels:
    app: airflow-webserver
    component: airflow
spec:
  type: LoadBalancer  # Exponer Airflow UI externamente
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: airflow-webserver
