name: Basic Test

on:
  push:
    branches: [ "main", "hito2" ]
  pull_request:
    branches: [ "main", "hito2" ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install dependencies
        run: |
          poetry install

      - name: Run tests
        run: |
          poetry run pytest -v


      - name: Show Docker logs
        if: always()
        run: |
          docker ps
          docker-compose -f docker/docker-compose.yml logs

      - name: Cleanup Docker
        if: always()
        run: |
          docker-compose -f docker/docker-compose.yml down